# Generated by Django 6.0 on 2025-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='aKpS4OHa81f3sdWF5Y7scNyI6OUFMv8Z', editable=False, max_length=32, unique=True),
        ),
    ]
